[package]
name = "rustrisn-t"
version = "0.0.1"
authors = ["Brian Billman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
mint = "0.5"