[package]
name = "rustrisn-t"
version = "0.0.1"
authors = ["Brian Billman"]
edition = "2018"

[profile.dev]
opt-level = 0
overflow-checks = false  # it's a feature, not a bug; overflow is used for player colors in tile.rs

[profile.release]
opt-level = 3

[dependencies]
ggez = "0.5"
rand = "0.7.3"