[package]
name = "rustrisn-t"
version = "0.0.1"
authors = ["Brian Billman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
ggez = "0.5"